// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoPkQ1wMi5T_o9ZJTrZtqOp-Jq66eu1ag',
    appId: '1:124657546718:web:4b33c255a1ee37551dd94f',
    messagingSenderId: '124657546718',
    projectId: 'in-classe',
    authDomain: 'in-classe.firebaseapp.com',
    storageBucket: 'in-classe.firebasestorage.app',
    measurementId: 'G-KWWJCPPZGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7YQ6udcCv-fMz6bGvNM9reXankXX3tKQ',
    appId: '1:124657546718:android:366db96cecdf556b1dd94f',
    messagingSenderId: '124657546718',
    projectId: 'in-classe',
    storageBucket: 'in-classe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJfmdV0rVN96nn7C0c-yLmIdTee8admM',
    appId: '1:124657546718:ios:f6dff2e3e44f34261dd94f',
    messagingSenderId: '124657546718',
    projectId: 'in-classe',
    storageBucket: 'in-classe.firebasestorage.app',
    iosClientId: '124657546718-e4jfln0kk5dqepvvjhin1pdlu59b0t4u.apps.googleusercontent.com',
    iosBundleId: 'it.univpm.inClasse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYJfmdV0rVN96nn7C0c-yLmIdTee8admM',
    appId: '1:124657546718:ios:f6dff2e3e44f34261dd94f',
    messagingSenderId: '124657546718',
    projectId: 'in-classe',
    storageBucket: 'in-classe.firebasestorage.app',
    iosClientId: '124657546718-e4jfln0kk5dqepvvjhin1pdlu59b0t4u.apps.googleusercontent.com',
    iosBundleId: 'it.univpm.inClasse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoPkQ1wMi5T_o9ZJTrZtqOp-Jq66eu1ag',
    appId: '1:124657546718:web:a9d14d4516b315e01dd94f',
    messagingSenderId: '124657546718',
    projectId: 'in-classe',
    authDomain: 'in-classe.firebaseapp.com',
    storageBucket: 'in-classe.firebasestorage.app',
    measurementId: 'G-0YDHP2JJ86',
  );

}